// Code generated by protoc-gen-go.
// source: motion.proto
// DO NOT EDIT!

/*
Package robots is a generated protocol buffer package.

It is generated from these files:
	motion.proto

It has these top-level messages:
	Gyro
	Mouv
*/
package roc

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Gyro struct {
	X float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
}

func (m *Gyro) Reset() {
	*m = Gyro{}
}
func (m *Gyro) String() string {
	return proto.CompactTextString(m)
}
func (*Gyro) ProtoMessage() {}
func (*Gyro) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

type Mouv struct {
	Speed float64 `protobuf:"fixed64,1,opt,name=speed" json:"speed,omitempty"`
	Angle float64 `protobuf:"fixed64,2,opt,name=angle" json:"angle,omitempty"`
}

func (m *Mouv) Reset() {
	*m = Mouv{}
}
func (m *Mouv) String() string {
	return proto.CompactTextString(m)
}
func (*Mouv) ProtoMessage() {}
func (*Mouv) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func init() {
	proto.RegisterType((*Gyro)(nil), "robots.Gyro")
	proto.RegisterType((*Mouv)(nil), "robots.Mouv")
}

func init() {
	proto.RegisterFile("motion.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcd, 0x2f, 0xc9,
	0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xca, 0x4f, 0xca, 0x2f, 0x29,
	0x56, 0x52, 0xe2, 0x62, 0x71, 0xaf, 0x2c, 0xca, 0x17, 0xe2, 0xe1, 0x62, 0xac, 0x90, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0c, 0x62, 0xac, 0x00, 0xf1, 0x2a, 0x25, 0x98, 0x20, 0xbc, 0x4a, 0x25, 0x23,
	0x2e, 0x16, 0xdf, 0xfc, 0xd2, 0x32, 0x21, 0x11, 0x2e, 0xd6, 0xe2, 0x82, 0xd4, 0xd4, 0x14, 0xa8,
	0x3a, 0x08, 0x07, 0x24, 0x9a, 0x98, 0x97, 0x9e, 0x93, 0x0a, 0x55, 0x0f, 0xe1, 0x24, 0xb1, 0x81,
	0xad, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x50, 0x52, 0x16, 0x43, 0x76, 0x00, 0x00, 0x00,
}
