// Code generated by protoc-gen-go.
// source: ai.proto
// DO NOT EDIT!

/*
Package rocproto is a generated protocol buffer package.

It is generated from these files:
	ai.proto
	gps.proto
	motion.proto
	proto.proto

It has these top-level messages:
	AiInfo
	Coord
	Gyro
	Mouv
	Packet
*/
package rocproto

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AiInfo_Codes int32

const (
	AiInfo_Empty      AiInfo_Codes = 0
	AiInfo_TAG        AiInfo_Codes = 32
	AiInfo_LOCK       AiInfo_Codes = 33
	AiInfo_UNLOCK     AiInfo_Codes = 34
	AiInfo_OBSTACLE   AiInfo_Codes = 35
	AiInfo_N_OBSTACLE AiInfo_Codes = 36
	AiInfo_LIGHT      AiInfo_Codes = 37
	AiInfo_DLIGH      AiInfo_Codes = 38
)

var AiInfo_Codes_name = map[int32]string{
	0:  "Empty",
	32: "TAG",
	33: "LOCK",
	34: "UNLOCK",
	35: "OBSTACLE",
	36: "N_OBSTACLE",
	37: "LIGHT",
	38: "DLIGH",
}
var AiInfo_Codes_value = map[string]int32{
	"Empty":      0,
	"TAG":        32,
	"LOCK":       33,
	"UNLOCK":     34,
	"OBSTACLE":   35,
	"N_OBSTACLE": 36,
	"LIGHT":      37,
	"DLIGH":      38,
}

func (x AiInfo_Codes) String() string {
	return proto.EnumName(AiInfo_Codes_name, int32(x))
}
func (AiInfo_Codes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type AiInfo struct {
}

func (m *AiInfo) Reset() {
	*m = AiInfo{}
}
func (m *AiInfo) String() string {
	return proto.CompactTextString(m)
}
func (*AiInfo) ProtoMessage() {}
func (*AiInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func init() {
	proto.RegisterType((*AiInfo)(nil), "rocproto.AiInfo")
	proto.RegisterEnum("rocproto.AiInfo_Codes", AiInfo_Codes_name, AiInfo_Codes_value)
}

func init() {
	proto.RegisterFile("ai.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0xcc, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0xca, 0x4f, 0x06, 0xb3, 0x94, 0xf2, 0xb9, 0xd8, 0x1c,
	0x33, 0x3d, 0xf3, 0xd2, 0xf2, 0x95, 0x52, 0xb9, 0x58, 0x9d, 0xf3, 0x53, 0x52, 0x8b, 0x85, 0x38,
	0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x05, 0x18, 0x84, 0xd8, 0xb9, 0x98, 0x43, 0x1c, 0xdd,
	0x05, 0x14, 0x84, 0x38, 0xb8, 0x58, 0x7c, 0xfc, 0x9d, 0xbd, 0x05, 0x14, 0x85, 0xb8, 0xb8, 0xd8,
	0x42, 0xfd, 0xc0, 0x6c, 0x25, 0x21, 0x1e, 0x2e, 0x0e, 0x7f, 0xa7, 0xe0, 0x10, 0x47, 0x67, 0x1f,
	0x57, 0x01, 0x65, 0x21, 0x3e, 0x2e, 0x2e, 0xbf, 0x78, 0x38, 0x5f, 0x05, 0x64, 0x8e, 0x8f, 0xa7,
	0xbb, 0x47, 0x88, 0x80, 0x2a, 0x88, 0xe9, 0x02, 0x62, 0x0b, 0xa8, 0x25, 0xb1, 0x81, 0xed, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x24, 0x7e, 0x57, 0xf9, 0x8d, 0x00, 0x00, 0x00,
}
