// Code generated by protoc-gen-go.
// source: protoext/robots/gps.proto
// DO NOT EDIT!

/*
Package robots is a generated protocol buffer package.

It is generated from these files:
	protoext/robots/gps.proto
	protoext/robots/motion.proto

It has these top-level messages:
	Coord
	Gyro
	Mouv
*/
package robots

import "github.com/golang/protobuf/proto"
import "fmt"
import "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Coord struct {
	Lat  float64 `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Long float64 `protobuf:"fixed64,2,opt,name=long" json:"long,omitempty"`
	Ori  float64 `protobuf:"fixed64,3,opt,name=ori" json:"ori,omitempty"`
}

func (m *Coord) Reset() {
	*m = Coord{}
}
func (m *Coord) String() string {
	return proto.CompactTextString(m)
}
func (*Coord) ProtoMessage() {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func init() {
	proto.RegisterType((*Coord)(nil), "robots.Coord")
}

func init() {
	proto.RegisterFile("protoext/robots/gps.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xad, 0x28, 0xd1, 0x2f, 0xca, 0x4f, 0xca, 0x2f, 0x29, 0xd6, 0x4f, 0x2f, 0x28, 0xd6,
	0x03, 0x8b, 0x09, 0xb1, 0x41, 0x44, 0x94, 0xec, 0xb9, 0x58, 0x9d, 0xf3, 0xf3, 0x8b, 0x52, 0x84,
	0x04, 0xb8, 0x98, 0x73, 0x12, 0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x18, 0x83, 0x40, 0x4c, 0x21,
	0x21, 0x2e, 0x96, 0x9c, 0xfc, 0xbc, 0x74, 0x09, 0x26, 0xb0, 0x10, 0x98, 0x0d, 0x52, 0x95, 0x5f,
	0x94, 0x29, 0xc1, 0x0c, 0x51, 0x05, 0x64, 0x26, 0xb1, 0x81, 0xcd, 0x33, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x28, 0x7a, 0x03, 0xe5, 0x6c, 0x00, 0x00, 0x00,
}
